### ISSUE TITLE
Could not find gem 'mechanize'

### ISSUE THREAD

**Issue by bh4017** [thuandt/flickr-photo-downloader#1]
I tried your program just now and I get the output below.  Unfortunately I am not familiar with ruby (in fact, yours is the first ruby program I've ever tried to execute!).

`/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:354:in`block in verify_gemfile_dependencies_are_found!': Could not find gem 'mechanize' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `each'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in`verify_gemfile_dependencies_are_found!'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:199:in `start'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:183:in`resolve'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in `resolve'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in`specs'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in`requested_specs'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in`setup'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
        from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in`require'
        from flickr-photo-downloader.rb:10:in `<main>'
`

**Comment by jbuckner** [comment]
I ran into this with OS X 10.13 High Sierra trying to use the system Ruby install. I was able to solve it by installing [RVM](https://rvm.io) and installing Ruby 2.4.1, then running:
```
gem install bundler
bundle install
```
